image: neshiraini/docbuild

before_script:
  - mkdir -p ~/.fonts
  - cp resources/OCRB.otf ~/.fonts/OCRB.otf
  - cp resources/MTCORSIVA.TTF ~/.fonts/MTCORSIVA.TTF
  - fc-cache -f -v

build:
  stage: build
  script:
    - make
  artifacts:
    name: "passports"
    paths:
      - pdf/*
