image: neshiraini/docbuild

before_script:
  - git lfs update && git lfs pull
  - mkdir -p ~/.local/share/fonts
  - cp resources/OCRB.otf ~/.local/share/fonts/OCRB.otf
  - cp resources/MTCORSVA.TTF ~/.local/share/fonts/MTCORSVA.ttf
  - chmod -R 755 ~/.local
  - chmod 644 ~/.local/share/fonts/*
  - fc-cache -f -v

build:
  stage: build
  script:
    - make
  artifacts:
    name: "passports"
    paths:
      - pdf/*
